### ISSUE TITLE
mumble and murmur fail to find SSL ciphers after openssl upgrade on Debian

### ISSUE THREAD

**Issue by crknadle** [mumble-voip/mumble#1876]
Since an upgrade to OpenSSL, mumble and murmur (mumble-server) fail to find the available SSL ciphers.  mumble-server does not start, and the mumble client also isn't willing to load a saved SSL certificate.

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804363

One possible fix supplied by the submitter is to add a call to 'SSL_library_init()' somewhere:

```
https://wiki.openssl.org/index.php/SSL/TLS_Client#Initialization
```

the submitter tested this via inserting the call during a gdb session and it seems to get around the issue.  I'd just like to insure that A) this is the correct fix, B) where the right place to insert the fix is.

Thanks much
-- Chris

**Comment by crknadle** [comment]
The following patch seems to be one way to fix most of the issue:

```
--- a/src/SSL.cpp
+++ b/src/SSL.cpp
@@ -49,6 +49,8 @@
 	QByteArray csbuf = cipherString.toLatin1();
 	const char *ciphers = csbuf.constData();
 
+	SSL_library_init();
+
 	meth = SSLv23_server_method();
 	if (meth == NULL) {
 		qWarning("MumbleSSL: unable to get SSL method");
```

However the mumble client still refuses to load my saved SSL certificate from a .p12 file.  I suspect this might have to do with something that was removed from the newer OpenSSL library in Debian; I won't know until I do a 'debdiff' comparison between the package versions.

**Comment by b4n** [comment]
I made some research and experiments, and it appears that `SSL_library_init()` has to be called somewhere before `g.s.load()` in `main()` for Mumble to fully work.  This is because `Settings::load()` calls `CertWizard::importCert()`, which itself calls a bunch of SSL functions (for X509/PKCS12 certificate loading) that require a properly initialized libssl.

I first tried to use a `DeferInit` to call this, but currently those initializers are called right *after* loading the settings, so no luck here.

In the end, I see two solutions (for Mumble, not necessarily Murmur):

1. Call `SSL_library_init()` directly from `main()`:
   ```diff
diff --git a/src/mumble/main.cpp b/src/mumble/main.cpp
index fb1b760..604685f 100644
--- a/src/mumble/main.cpp
+++ b/src/mumble/main.cpp
@@ -124,6 +124,8 @@ int main(int argc, char **argv) {
 
        qsrand(QDateTime::currentDateTime().toTime_t());
 
+       SSL_library_init();
+
 #if defined(Q_OS_WIN) || defined(Q_OS_MAC)
        os_init();
 #endif
```
2. Use a `DeferInit` in *SSL.cpp* but move `DeferInit::run_initializers()` call before `Settings::load()`:
   ```diff
diff --git a/src/SSL.cpp b/src/SSL.cpp
index bf86749..0397638 100644
--- a/src/SSL.cpp
+++ b/src/SSL.cpp
@@ -32,8 +32,19 @@
 
 #include "SSL.h"
 
+#include "Global.h"
 #include "Version.h"
 
+class SSLInit : public DeferInit {
+	public:
+		void initialize() {
+			SSL_library_init();
+		};
+		void destroy() {};
+};
+
+static SSLInit sslinit;
+
 QString MumbleSSL::defaultOpenSSLCipherString() {
 	return QLatin1String("EECDH+AESGCM:EDH+aRSA+AESGCM:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA");
 }
diff --git a/src/mumble/main.cpp b/src/mumble/main.cpp
index fb1b760..bbd60f4 100644
--- a/src/mumble/main.cpp
+++ b/src/mumble/main.cpp
@@ -292,6 +292,8 @@ int main(int argc, char **argv) {
 		}
 	}
 
+	DeferInit::run_initializers();
+
 	// Load preferences
 	g.s.load();
 
@@ -309,8 +311,6 @@ int main(int argc, char **argv) {
 	}
 #endif
 
-	DeferInit::run_initializers();
-
 	ApplicationPalette applicationPalette;
 	
 	Themes::apply();
```
   This is a slightly more contained approach.

However, I'm afraid neither of these solutions will fix Mumur, as the first would require to also introduce a manually call in Murmur initialization, and the second depends on `DeferInit` that is part of Mumble only.

**Comment by mkrautz** [comment]
Is this OpenSSL 1.0.2 and Qt 4?

**Comment by mkrautz** [comment]
Yes it is, per the bug report.

**Comment by crknadle** [comment]
In both the before-and-after case it's OpenSSL 1.0.2d -- same exact upstream version of OpenSSL, the only differences are the Debian packaging.  That's why I'm looking at the differences between openssl_1.0.2d-1 and openssl_1.0.2d-3.

**Comment by crknadle** [comment]
I've looked through the differences between Debian's openssl 1.0.2d-1 vs 1.0.2d-3, but I don't see anything in the changes that looks like a problem.  I've opened a bug on the openssl package to let the maintainers know of the issue and in case they can help.

**Comment by mkrautz** [comment]
Well, it does seem odd for Mumble not to explicitly initialize OpenSSL with its various init calls.

Before 1.2.10, we didn't have the cipher selection stuff, and so our initialization was handled by Qt.

Now, on some platforms, we might call QSsl-related functions that initialize OpenSSL for us, before we do the cipher suite selection stuff. But I am not sure if that happens on all platforms. I don't think it happens on Linux.

But, if you say that 1.2.10 worked previously, I am not sure that is what is going on...

**Comment by crknadle** [comment]
1.2.10 worked on Debian previously, that I'm sure.  And more oddly, 1.2.10 worked with openssl_1.0.2d-3 /until/ it was rebuilt with it via a binNMU -- then it didn't. This is testable because Debian has snapshots of every build: 

    http://snapshot.debian.org/package/mumble/1.2.10-2/

Both versions are in that page -- the mumble_1.2.10-2_amd64.deb package works correctly, the mumble_1.2.10-2+b1_amd64.deb package does not, and there's been no change to the mumble package.  ??

**Comment by hamilton5** [comment]
I can confirm downgrading debian packages fixes the problem.

**Comment by crknadle** [comment]
The Qt package versions didn't change between the "good" and "bad" builds.  One thing I did note though is that libssl-dev pulled in both libssl1.0.0 and libssl1.0.2, but 'ldd' shows that only libssl1.0.2 is linked to in the resulting binary.

**Comment by crknadle** [comment]
Seems to me like os_init() should execute before initializing the SSL library; I tried the following patch which works for both mumble and mumble-server:

```c++
--- a/src/mumble/main.cpp
+++ b/src/mumble/main.cpp
@@ -170,6 +170,8 @@
 	os_init();
 #endif
 
+	SSL_library_init();
+
 	bool bAllowMultiple = false;
 	QUrl url;
 	if (a.arguments().count() > 1) {
--- a/src/murmur/main.cpp
+++ b/src/murmur/main.cpp
@@ -203,6 +203,8 @@
 	qsrand(QDateTime::currentDateTime().toTime_t());
 	qInstallMsgHandler(murmurMessageOutput);
 
+	SSL_library_init();
+
 #ifdef Q_OS_WIN
 	Tray tray(NULL, &le);
 #endif
```

The single call in main() seems cleaner to me than making the call inside run_initilizers() [though I had the same thought of trying to put it there].

@mkrautz: does this patch look okay to you?  i.e. Do you think it would be okay to upload a Debian package that uses this patch?

**Comment by mkrautz** [comment]
That should be fine, for both mumble and murmur.

But I believe the correct "dance" to initialize OpenSSL is something like this:
https://github.com/mumble-voip/libmumble/blob/master/src/OpenSSLUtils.cpp#L19

**Comment by crknadle** [comment]
Based on the link Colomban had provided in the bug

   https://wiki.openssl.org/index.php/SSL/TLS_Client#Initialization

... a calls to ERR_load_crypto_strings() and OpenSSL_add_ssl_algorithms() aren't needed, leaving two calls:

```c++
   SSL_library_init();
   SSL_load_error_strings();
```

I'll update the patch for Debian with SSL_load_error_strings() and likely make a release this evening.

**Comment by trustable-code** [comment]
For me the problem is fixed with Mumble 1.2.10-3 (Debian Testing)

**Comment by crknadle** [comment]
@trustable-code: thanks for the verification.  The reason to leave this bug open is to allow the mumble project track when they've made a commit to the code for fixing the issue (rather than only fixing the mumble package Debian).  If that's been done then obviously this bug can be closed.

**Comment by mkrautz** [comment]
@crknadle I tried to reproduce this, in order to include a fix in 1.2.13.

However, so far I have failed.

I just built the 1.2.x branch on an up-to-date sid as of 2016-02-07.
I was able to use Murmur and Mumble just fine without any patches.

**Comment by crknadle** [comment]
Mikkel Krautz:
> @crknadle I tried to reproduce this, in order to include a fix in 1.2.13.
> 
> However, so far I have failed.
> 
> I just built the 1.2.x branch on an up-to-date sid as of 2016-02-07.
> I was able to use Murmur and Mumble just fine without any patches.

If this isn't reproducible on the /current/ sid (i.e. with the latest
openssl package), that isn't surprising -- mumble went for years without
triggering the bug.  The only way I know to test this is to build mumble
against the /specific/ version of openssl in Debian that showed the issue --
version 1.0.2d-3, which can be downloaded here:

   http://snapshot.debian.org/package/openssl/1.0.2d-3/

In November I attempted to track down what it was about the 1.0.2d-3 openssl
package that caused mumble to break, and ran into trouble doing so because
when mumble can't connect to SSL it ends up re-creating an empty SSL
certificate and also overwrites the automatic backup file too:

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804487#62

Also note that if you're trying to build mumble using cowbuilder or
pbuilder, one or both of them have a bug where they don't seem to respect
Apt PIN priority to use an older version of a package placed in a local
repository over a newer version in another repository.  The two ways I know
to work around that bug are either to switch to sbuild, or to modify the
openssl 1.0.2d-3 source package to place an epoch in the version number
(i.e. version # 2:1.0.2d-3) so that the version number will be higher than
what's in Debian's repository so that cowbuidler will use it.

   -- Chris

-- 
Chris Knadle
Chris.Knadle@coredump.us

**Comment by mkrautz** [comment]
Re-opening. I hadn't meant to include the "Fixes ..." line in the commit, because the bug isn't fixed. (The bug was with 1.2.x on newer OpenSSLs -- we think)

**Comment by mkrautz** [comment]
@crknadle I assume that, at no point has it been possible for Mumble to load two different OpenSSL's into its address space?

I note that the original Debian bug talks about a change in soname. Was there ever a time where both the new and the old package's shared libraries were available on the filesystem at the same time?

I ask because, Qt will, in its default configuration, dlopen OpenSSL. But Mumble is dynamically linked against OpenSSL. If more than one libssl.so/libcrypto.so is available on the system, things can go wrong. If Mumble gets into a state where those two version are loaded into the address space, and they are distinct binaries, it'll have two different versions loaded at the same time.

This can cause problems, such as crashes (at least on FreeBSD, I am not sure how things would behave on Debian).

I also think it could, say, cause the one loaded by Qt to get initialized correctly, while the one linked against Mumble itself wouldn't be. (Maybe).
Or, just weird behavior in general, because some opaque structures were changed, or who knows what.

I am not sure it is relevant, since I can't see how we'd ever load two different OpenSSL versions on Debian -- and especially not since both were OpenSSL 1.0.2. I can't see how they'd ever be on the system at the same time.

**Comment by mkrautz** [comment]
I have just confirmed that my above assumption is true:

I,

1. Observed that both libssl.so.1.0.0 and libcrypto.so.1.0.2 are on in /usr/lib/$triple
2. Renamed the symlink for libcrypto.so from libcrypto.so.1.0.2 to libcrypto.so.1.0.0
3. Renamed the symlink for libssl.so from libssl.so.1.0.2 to libcrypto.so.1.0.0
4. Rebuilt Mumble. Mumble is now linked against libcrypto.so.1.0.0 and libcrypto.so.1.0.0.
5. Ran Mumble. Observed that it crashes as you describe.

So, what made the bug appear is that your original Mumble build was linked against libssl.so.1.0.0 and libcrypto.so.1.0.0 (which the old OpenSSL package provided, via its -dev packages). After upgrading OpenSSL, the Mumble binary was still linked against libsso.so.1.0.0 and libcrypto.so.1.0.0, BUT Qt loaded libcrypto.so.1.0.2 and libcrypto.so.1.0.2, presumably because that's what the libcrypto.so and libssl.so symlinks pointed to.

**Comment by crknadle** [comment]
> @crknadle I assume that, at no point has it been possible for Mumble to load two different OpenSSL's into its address space?

I think that's the case, but it's a bit complicated and so hard to be sure.  It **is** possible to have multiple libssl packages installed (such as -- I have libssl1.0.0 and libssl1.0.2 both installed right now), and if I understand correctly packages built against libssl1.0.0 will use that, and packages built against libssl1.0.2 will use that.  (Or at least that's what's supposed to happen.)

The way to check this is to run 'ldd' on the resulting binary, i.e. 'ldd /usr/bin/mumble | fgrep libssl' whereby you'll see that mumble is dynamically linked against only **one** version of libssl even though multiple libssl libraries may be installed.

> I note that the original Debian bug talks about a change in soname. Was there ever a time where both the new and the old package's shared libraries were available on the filesystem at the same time?

One of the things I noted about this is that both libssl1.0.0 and libssl1.0.2 were pulled into the buildd for the mumble 1.2.10-2+b1 binNMU and I asked the openssl maintainer about that, he assured me that this was a red herring:

   https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=804487#20

**Comment by crknadle** [comment]
Mikkel Krautz:
> I have just confirmed that my above assumption is true:
> 
> I,
> 
> 1. Observed that both libssl.so.1.0.0 and libcrypto.so.1.0.2 are on in /usr/lib/$triple
> 2. Renamed the symlink for libcrypto.so from libcrypto.so.1.0.2 to libcrypto.so.1.0.0
> 3. Renamed the symlink for libssl.so from libssl.so.1.0.2 to libcrypto.so.1.0.0
> 4. Rebuilt Mumble. Mumble is now linked against libcrypto.so.1.0.0 and libcrypto.so.1.0.0.
> 5. Ran Mumble. Observed that it crashes as you describe.
> 
> So, what made the bug appear is that your original Mumble build
> was linked against libssl.so.1.0.0 and libcrypto.so.1.0.0 (which
> the old OpenSSL package provided, via its -dev packages). After
> upgrading OpenSSL, the Mumble binary was still linked against
> libsso.so.1.0.0 and libcrypto.so.1.0.0, BUT Qt loaded
> libcrypto.so.1.0.2 and libcrypto.so.1.0.2, presumably because that's
> what the libcrypto.so and libssl.so symlinks pointed to.

Hmm, well -- mumble built against openssl 1.0.2d-2 worked fine with openssl
1.0.2d-3 libraries installed, but did not work when **built** with openssl
1.0.2d-3.  My understanding is that this is because mumble 1.2.10-2 in
Debian was still using libssl1.0.0, where after the binNMU mumble
1.2.10-2+b1 started using libssl1.0.2 whereby it broke.  Adding in a patch
to initialize SSL fixed mumble with 1.2.10-3, linked against libssl1.0.2.

I don't think it was "loading the wrong libssl library" that caused mumble
to break in Debian.  I still believe it was something specific with the
changes in the openssl 1.0.2d-3 package that triggered the bug, but I
haven't gotten down to exactly what changes did that.  Mumble when built
with openssl 1.0.2d-2 worked, and when built with openssl 1.0.2d-3 did not,
and that's repeatable (after understanding the odd certificate wizard
behavior that results).

If having multiple libssl libraries installed would itself break mumble then
the symptoms of that should be that none of the versions I've been using
from 1.2.10-3 to now would work reliably -- and they do.

Something else to consider: LibreSSL vs OpenSSL.  If mumble upstream inserts
a sanity check to insure that the SSL library that's loaded has to match the
version that it was built against, then if mumble were built against OpenSSL
but LibreSSL were used in place of OpenSSL (the sonames between these SSL
implementations are different), mumble would likely reject this but I think
we'd all want that to work.

**Comment by mkrautz** [comment]
Chris,

The problem is that Mumble links against OpenSSL at build time, and Qt in Debian is configured without -openssl-linked, so it loads OpenSSL at runtime via dlopen().

If these are built against different openssl -dev packages, Mumble and Qt will load conflicting OpenSSL shared libraries into the address space, and things go terribly wrong.

I see that your bug report, you write:

> Let me be more specific: mumble_1.2.10-2 that was built with
> openssl_1.0.2d-1 works fine with openssl 1.0.2d-3 installed -- yet
> mumble_1.2.10-2+b1 that was /built/ with openssl_1.0.2d-3 does not.

This means we have the following scenario, which works:

1. mumble_1.2.10-2 is built against openssl_1.0.2d-1 (soname 1.0.0)
2. mumble_1.2.10-2 It works fine with openssl 1.0.2d-3 installed, even when built against openssl_1.0.2d-1
3. This suggests that the system has libssl.so.1.0.0 and libcrypto.so.1.0.0 on it, as well as libssl.so.1.0.2 and libcrypto.so.1.0.2.
3. ldd /usr/bin/mumble shows libcrypto.so.1.0.0 and libssl.so.1.0.0
4. Qt 4 is presumably was presumably also built against openssl_1.0.2d-1 (soname 1.0.0); this means that opensslv.h's SHLIB_VERSION_NUMBER is set to 1.0.0 -- and Qt will prioritize libraries with the 1.0.0 soname when doing dlopen() via QLibrary.
5. Everything works. Neither of libcrypto.so.1.0.2 and libssl.so.1.0.2 are used anywhere in Qt or Mumble.

Now. What broke things for you was rebuilding Mumble against openssl 1.0.2d-3's -dev package.

In that scenario, the following would happen:

1. mumble_1.2.10-2 is built against openssl 1.0.2d-3 (soname 1.0.2)
2. ldd /usr/bin/mumble shows libcrypto.so.1.0.2 and libssl.so.1.0.2
3. Let us say that Qt has not yet been rebuilt, and is still built against openssl_1.0.2d-1 (soname 1.0.0). SHLIB_VERSION_NUMBER is still 1.0.0, so Qt gives priority to libcrypto.so.1.0.0 and libssl.so.1.0.0. Since they're available on the system, it uses these.
4. Everything is broken. Now we have two OpenSSL's in the address space.

I would be very surprised if this is not the issue you encountered.
If you would like to try this yourself, try running the broken Mumble binary, and check the output of

    cat /proc/`pidof mumble`/maps | grep "lib\(ssl\|crypto\)"

Thanks!

**Comment by mkrautz** [comment]
Here's the nitty-gritty on how Qt loads OpenSSL:

https://github.com/qtproject/qtbase/blob/dev/src/network/ssl/qsslsocket_openssl_symbols.cpp#L624-L727

The gist of it is, when built WITHOUT -openssl-linked, Qt will prioritize the SHLIB_VERSION_NUMBER (defined in openssl/opensslv.h) that was present in the headers when it was built.

So if Qt is built against a 1.0.0 soname, and Mumble against a 1.0.2 soname, and both are present on the system -- things WILL go wrong.

**Comment by Krzmbrzl** [comment]
Given that 1.2 is veeeeery old by now and has been replaced by the newer 1.3 release (plus the fact that there has been a commit addressing this), I'll assume this issue is fixed by now (or at least outdated and didn't occur afterwards)
