### ISSUE TITLE
Using Mumble 1.2.15 makes my mouse input very laggy

### ISSUE THREAD

**Issue by rick9791** [mumble-voip/mumble#2166]
For some reason, Mumble 1.2.15 makes my mouse input very slow, a friend of mine has got the same issue.

I uninstalled 1.2.15 and went back to 1.2.14, now my mouse input is alright. Just a headsup to anyone who has got the same issue on 1.2.15.

**Comment by mkrautz** [comment]
Hi,

Sorry about that.  We haven't had other reports about that particular issue.

It would help a lot if you could provide a Mumble log when running 1.2.15.  Simply run 1.2.15, wait a short while, and close Mumble again after reproducing the issue.

Then, open the file %APPDATA%\Mumble\Console.txt and copy/paste the contents of the file into a Gist (https://gist.github.com/) and link it in this issue.

Also, if you can, your DXDIAG output would also help. (Run "dxdiag.exe", choose "Save all information").

Thanks!

**Comment by rick9791** [comment]
Mumble log: https://gist.github.com/rick9791/0c76076e8ed50f47f991
DXDIAG: https://gist.github.com/rick9791/e330df3124c9c1a3d382

**Comment by mkrautz** [comment]
Nothing useful from the log.

@rick9791 Can you please try to disable XboxInput in Mumble 1.2.15?

Save this as a .reg file and apply it:  (disable-xboxinput.reg)

    Windows Registry Editor Version 5.00
    
    [HKEY_CURRENT_USER\SOFTWARE\Mumble\Mumble\shortcut\windows\xbox]
    "enable"="false"

To remove again afterwards (if needed):   (default-xboxinput.reg)

    Windows Registry Editor Version 5.00
    
    [HKEY_CURRENT_USER\SOFTWARE\Mumble\Mumble\shortcut\windows\xbox]
    "enable"=-

If the registry fix to disable XboxInput works, then I suppose we'll have to not poll for Xbox controllers when none are present on the system...

**Comment by LaMqTa** [comment]
I am also having this problem. No idea whats causing it, will try to disable xboxinput!

**Comment by mkrautz** [comment]
You can use the following zip file:

[xboxinput-reg.zip](https://github.com/mumble-voip/mumble/files/167565/xboxinput-reg.zip)

Just run disable-xboxinput.reg, and try again!

**Comment by mkrautz** [comment]
Have anyone tried disabling XboxInput with the supplied .reg file?

**Comment by LaMqTa** [comment]
Sorry for the delay, i've been busy with some other stuff lately. And ye, i just tested it and it seems that the xboxinput has been doing this issue. :/ Thanks for the help!

**Comment by mkrautz** [comment]
@LaMqTa What version of Mumble were you using when this happened to you?

Were you on 1.2.15, without an Xbox controller attached?

And using the .reg file fixed the issue?

Because if you were on an earlier release, (with an Xbox controller), then simply upgrading to 1.2.15 should have worked.

Which one was it? Thanks!

**Comment by LaMqTa** [comment]
Sorry..it just happened again, with xboxinput disabled. :/ And ye i just have updated to 1.2.15 without Xbox controller.

**Comment by mkrautz** [comment]
@LaMqTa Does Mumble use a lot of CPU%?

**Comment by LaMqTa** [comment]
Not more than usual

**Comment by mkrautz** [comment]
@LaMqTa Does the issue disappear when going back to 1.2.14 for you as well?

The majority of the changes in 1.2.15 are related to XInput support. I don't see any of the other changes having the ability to make the issue at hand appear.

I will try to do some custom builds of 1.2.15 soon, with some of the new changes removed. I hope we can find the culprit that way.

**Comment by LaMqTa** [comment]
Ye, it does disappear when going back to 1.2.14. 
Alright, thanks! :)

**Comment by lennyxc** [comment]
Found this and wanted to report a similar situation and that disable-xboxinput.reg fixed it. 

Had issues with input lag from mouse and keyboard (e.g. pressing back in my browser while moving my mouse immediately afterwards in circles showed lots of lag for a second or 2 / typing seemed to lag more than normal). Confirmed closing Mumble 1.2.15 got rid of input lag.

Ran the reg file to disable XboxInput and tested with Mumble open and it seems input lag issues are now fixed.

**Comment by mkrautz** [comment]
@lennyxc And you don't have an Xbox controller connected to your system? (Just making sure... The 'fix' would be to not poll XInput when no Xbox controllers are connected...)

**Comment by lennyxc** [comment]
Correct, I don't have a Xbox controller.

On Sunday, April 17, 2016, Mikkel Krautz <notifications@github.com> wrote:

> @lennyxc <https://github.com/lennyxc> And you don't have an Xbox
> controller connected to your system? (Just making sure... The 'fix' would
> be to not poll XInput when no Xbox controllers are connected...)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mumble-voip/mumble/issues/2166#issuecomment-210989514>
>


--

**Comment by mkrautz** [comment]
FWIW, there's a PR to potentially fix this issue:
https://github.com/mumble-voip/mumble/pull/2238

**Comment by mkrautz** [comment]
We've backported the PR I mentioned to a new 1.2.x release. It's available in 1.2.16.

Please report back if 1.2.16 is still broken for you. Thanks!
