### ISSUE TITLE
Events show up in the sidebar but are not actually sent to the server

### ISSUE THREAD

**Issue by asayers** [mumble-voip/mumble#4170]
**Describe the bug**

The client can get into a state where events show up in the sidebar but are not actually sent to the server.  This state appears to last until the client is restarted.

**Describe what you actually saw**

Roughly once a day the affected user will try to perform some action (like unmuting) and discover that it had no effect.  For instance: he might click the toggle-mute button, and see an "unmuted" entry appear in the sidebar, but the muted icon remains next to his name.  There's no "unmuted" event in the server log or anyone else's client, and he is in fact muted still.  Once his client is in this state, it seems that he can't make any changes - toggle-deafen, change room, etc. exhibit the same behaviour: an entry appears in the sidebar but noone else sees it and the change is not made.  We have confirmed that the client doesn't fix itself, even after a few minutes.

**Steps to Reproduce**

I don't know yet how to trigger this bad state.

**Expected behavior**

I expect everyone to see the same set of events in their sidebar, and in the server log.

**Screenshots**

Here's the buggy client (OS X) - note that the user (simon) has toggled the mute state three times at 09:01:
![Screen Shot 2020-05-14 at 9 01 27](https://user-images.githubusercontent.com/877109/81878619-88880b80-95c3-11ea-918f-8b18ed4685d4.png)

Here's the server log for that time period - those events are missing:

```
<W>2020-05-14 08:55:58.503 1 => <32:fumieval(-1)> Authenticated
<W>2020-05-14 08:55:58.532 1 => <32:fumieval(-1)> Moved fumieval:32(-1) to traders[1:0]
<W>2020-05-14 09:01:50.958 1 => <172:simon(7)> Connection closed: The remote host closed the connection [1]
<W>2020-05-14 09:01:58.823 1 => <34:(-1)> New connection: 124.155.105.194:58198
<W>2020-05-14 09:01:58.841 1 => <34:(-1)> Client version 1.3.0 (X11: 1.3.0)
<W>2020-05-14 09:01:58.852 1 => <34:Mateusz(3)> Authenticated
```

And here's my client - the events are missing here too:
![mumble](https://user-images.githubusercontent.com/877109/81878599-7c03b300-95c3-11ea-8a78-58eb263804d3.png)

**Desktop (please complete the following information):**

This issue is only affecting one user.  He's running:

 - OS: MacOS 10.15.4
 - Version: Mumble 1.3.0 and 1.3.1 rc1 - issue observed on both
 - Server: Murmur 1.3.0+dfsg-1build1 from Ubuntu 20.04

**Additional context**

At first I thought it may be due to event rate-limiting (which is why I asked the affected user to upgrade to 1.3.1rc1).  However this doesn't seem to be it, because once the client has stopped sending events it seems to be stuck in the state permanently.  I asked the affected user to wait a few minutes and try unmuting, but he was still unable to.

I know that restarting the client fixes the issue.  Next time it happens we'll check whether disconnecting/reconnecting to the server is sufficient.

**Comment by Krzmbrzl** [comment]
> At first I thought it may be due to event rate-limiting (which is why I asked the affected user to upgrade to 1.3.1rc1).

I'm like 99% certain that this is indeed the rate limiter kicking in. That is independent from the used client though. That's on the server-side.

> Server: Murmur 1.3.0+dfsg-1build1 from Ubuntu 20.04

What kind of version is that? Is that one of the old 1.3.0 snapshot releases or is this actually the officially released 1.3.0 version?
In any case, we fixed some issues with the rate limiter in 1.3.1 (which should be released in the coming days or so, but you can try out 1.3.1.rc1 already). Could you check and see whether the issue persists with the 1.3.1 server?

**Comment by asayers** [comment]
Some updates: Once the bad state is triggered, neither muting/unmuting nor changing rooms works.  Simply disconnecting and reconnecting to the server is enough to fix it (client restart is not required).  We can't trigger the issue by spamming mute - we still don't have a reliable repro.

> > Server: Murmur 1.3.0+dfsg-1build1 from Ubuntu 20.04
>
> What kind of version is that?

That's just the version which comes with Ubuntu 20.04 ([this guy](https://packages.ubuntu.com/focal/mumble-server)).

> Could you check and see whether the issue persists with the 1.3.1 server?

Will do.

**Comment by asayers** [comment]
Since upgrading the server to 1.3.1rc1 last week we haven't seen the issue again, so it looks like it's fixed!  I guess it _was_ the rate-limiting issue after all.  Thanks @Krzmbrzl

**Comment by Krzmbrzl** [comment]
Awesome! Thanks for reporting back :)
