### ISSUE TITLE
Echo in Voice Activity/Continuous  Transmit Mode

### ISSUE THREAD

**Issue by bariamdadul** [mumble-voip/mumble#4573]
When Voice Activity or Continous transmit mode is selected, I can hear the second party clearly and also hear my voice back. 
I am not sure whether the server is returning my voice back to me or it's an issue of my clients. 

I am facing the issue on Linux, Windows, Android, and IOS clients. 

Tested with Murmur server 1.3.3 and the latest one. 

Anyone facing the same issue? How to overcome this? 

Here is the audio configuration of my mumble client. 

![audio1](https://user-images.githubusercontent.com/33399713/98625092-3852f180-2339-11eb-8126-44bb458383f8.png)

![audio2](https://user-images.githubusercontent.com/33399713/98625114-3f79ff80-2339-11eb-946c-2b29d061f436.png)

**Comment by Krzmbrzl** [comment]
From your report I take it that the echo is not seen when you use push-to-talk. Is that correct?

Also are you always speaking with the same clients when the echo happens? Do these clients use a headset or do they output the received audio via a speaker?

Iirc echo cancellation in Mumble 1.3.x is broken. The feature has been fixed in current master (1.4.0) but were too involved to be backported to the 1.3.x series...

**Comment by bariamdadul** [comment]
1. Echo is not happening when I use push-to-talk. 

2. All clients are using headsets. 

3. Should I update my clients to the 1.4.0 version?

**Comment by Krzmbrzl** [comment]
If it is not happening with PTT, then this does indeed seem to be a different issue :eyes: 

Does the problem also occur on different Mumble servers?

Checking out 1.4.0 could be worth a try. Note however that we haven't released any binaries yet. We are currently in the process of preparing the first snapshot releases but until then you'd have to either compile it yourself or if you're on Windows or mac, you could use one of the binaries built on our CI servers. These are more or less untested though and therefore likely to still contain bugs :point_up:

**Comment by bariamdadul** [comment]
Tested with the latest 1.4 murmur server in Ubuntu 18.04 but still facing the same issue.

**Comment by Krzmbrzl** [comment]
> Does the problem also occur on different Mumble servers?

:point_up: 

Also: Does this issue also happen when you're alone in a channel or only if you are speaking to someone else?

**Comment by imShara** [comment]
Is there way to cancel echo if someone uses speaker instead headset?

**Comment by davidebeatrici** [comment]
Yes, you can enable the echo cancellation feature.

**Comment by bariamdadul** [comment]
> Also: Does this issue also happen when you're alone in a channel or only if you are speaking to someone else?

It happens only when multiple people are talking at the same time. If one person is muted and another person is talking then I don't face this issue.

**Comment by Krzmbrzl** [comment]
> If it is not happening with PTT, then this does indeed seem to be a different issue

Nvm - that's actually not correct. It does make sense that the echo does not appear when PTT is used :facepalm: 

> Tested with the latest 1.4 murmur server in Ubuntu 18.04 but still facing the same issue.

You conversation partner has to use 1.4.0 as well **and** enable echo cancellation.

> It happens only when multiple people are talking at the same time. If one person is muted and another person is talking then I don't face this issue.

Okay then I am 99% sure this is due to either your conversation partners not having echo cancellation enabled or due to them using a version < 1.4.0 of Mumble in which echo cancellation has some issues.
