### ISSUE TITLE
Plugin Framework / Updater: possible regression

### ISSUE THREAD

**Issue by hbeni** [mumble-voip/mumble#4946]
**Describe the bug**
Hi Robert, sorry to bother again, but I possibly found a regression that did not happen in your branch regarding the updater.
I reproduced it with yesterdays nighly.
The affected OS is at least Windows.

There are some problems, probably related:
- [x] Installation of ZIP release fails with the message like "no plugin for current OS found", despite beeing in the ZIP.
  (Naming Issue: partly solved by just packaging only a single binary dll/so/bundle type per target OS)
- [x] Manually trying to install the release ZIP through the plugin options yields some obscure message "invalid ZIP header"
  (unknown so far)
- [x] Manually extracting and then selecting the .dll does yield in a problem with the file in there not overwritable in AppData/Roaming.
  (probably the plugin is not unloaded in a complete or timely manner, still locking the library)
- Deleting the problematic file there and then manually selecting the .dll does work.

**Steps to Reproduce**
1. Download previous plugin version binary-only distribution zip: https://github.com/hbeni/fgcom-mumble/releases/download/v.0.11.0/fgcom-mumble-client-binOnly-0.11.0.zip
2. Try to install it through the plugin options
3. If sucessfull (see above description), restart mumble. The updater will pick up the more recent 0.12.0. plugin.
4. Download fails.
5. Manually installing 0.12.0 like described above does work (https://github.com/hbeni/fgcom-mumble/releases/download/v.0.12.0/fgcom-mumble-client-binOnly-0.12.0.zip).

**Expected behavior**
I expect both the installer and updater to succesfully retrieve, unzip and install the appropriate plugin file.

**Additional context**
For the 0.12.0 files I do not build the binarys locally, but use GitHubs Actions for it. This also introduces the new file `fgcom- mumble-macOS.so` into the release ZIP.
Upgrading from 0.10.0 to 0.11.0 worked with your plugin-branch.

@Krzmbrzl

**Comment by hbeni** [comment]
I just checked with self compiled current master () on linux and there it works.

But there i got another problem: `[10:18:04] Found more than one plugin library for the current OS in "fgcom-mumble-client-binOnly-0.12.0.zip" ("fgcom-mumble-macOS.so" and "fgcom-mumble.so")!`
That's surely just a naming problem, but how are plugin libraries extensions to be called on mac?

**Comment by Krzmbrzl** [comment]
> That's surely just a naming problem, but how are plugin libraries extensions to be called on mac?

I always thought `.dylib` but according to https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-macos it should be `.bundle`. However `.so` is also permissible and therefore my check is bogus xD

**Comment by hbeni** [comment]
OK Thank you. What should i do on the naming issue: Are you refining the check, or should i rename, or both?

**Comment by Krzmbrzl** [comment]
> Are you refining the check, or should i rename, or both?

Both I would say :D

**Comment by hbeni** [comment]
Did rename in for the next builds.
I hope this still works - the compilation stayed the same.

@fdalvi

**Comment by hbeni** [comment]
Update: Renaming to `.bundle` does work at least for the linux updater, which can now again source it's pugin binary.
Still no clue if the `.bundle` plugin works on MacOS tough.

**Comment by fdalvi** [comment]
Works perfectly @hbeni, I didn't even need to worry about the quarantine stuff this time (maybe it doesn't apply to *bundles). I was still not able to successfully test using the echo mode, not sure if its still a server side issue. Can you confirm it works on your end?

**Comment by hbeni** [comment]
> Works perfectly @hbeni, I didn't even need to worry about the quarantine stuff this time (maybe it doesn't apply to *bundles)

Thats indeed some very good news!

> Can you confirm it works on your end?

Just tested: works as designed. You were in the `fgcom-mumble` channel, weren't you (thats important, the plugin and also the bots are not active outside it)?

**Comment by hbeni** [comment]
@Krzmbrzl 
The updater on linux now again works.
Windows is stuck still, however.

**Comment by fdalvi** [comment]
> Just tested: works as designed. You were in the `fgcom-mumble` channel, weren't you (thats important, the plugin and also the bots are not active outside it)?

Yes, I was in the channel and tuned my (ufo) radio to 910 as well. I see myself on the status page as well.

Not sure what else could be the issue here then, maybe we can try together at some point to make sure the bot is not the issue?

**Comment by hbeni** [comment]
(split off to hbeni/fgcom-mumble#105 i order to keep this here clean)

**Comment by Krzmbrzl** [comment]
> Is the updater just comparing the extension?

Yes. It doesn't care about your library's name because I thought comparing extensions would be sufficient. In the end I guess the issue here is that macOS and Linux libraries (the `.so` ones that is) are actually compatible whereas my original assumption was that every platform does have its own format for shared libraries that are incompatible with other platforms.

I'll have to look into this but I guess that I'll also check the name of the library for suffixes like `_win`, `_mac` and `_linux` or something like that :thinking:

**Comment by Krzmbrzl** [comment]
@hbeni FOr my test case even the 0.11 version failed to install from the zip. My suspicion is that maybe there is some issue with the fact that there are 2 windows plugins in there: One 64bit and one 32bit version. Have you checked whether the issue persists when removing that second plugin?

**Comment by hbeni** [comment]
> I'll also check the name of the library for suffixes like _win, _mac and _linux or something like that

wouldn’t be a better/more safe approach be to get the file signature to determine type, like the file command does on linux?

> Have you checked whether the issue persists when removing that second plugin?

not yet, but good idea!

**Comment by Krzmbrzl** [comment]
> wouldn’t be a better/more safe approach be to get the file signature to determine type, like the file command does on linux?

Yes but that would still yield the issue that we're seeing right now were macOS binaries can be loaded on Linux and thereby creating problems

**Comment by hbeni** [comment]
Indeed!
But that could be mitigated by the extension check when using .bundle, which was also the right thing because of the quarantine inssue

**Comment by hbeni** [comment]
> * Manually extracting and then selecting the .dll does yield in a problem with the file in there not overwritable in AppData/Roaming.

Just for completeness, this is the error:
![grafik](https://user-images.githubusercontent.com/13608602/118414655-3d0caf80-b6a6-11eb-940d-b63d30e61421.png)

**Comment by hbeni** [comment]
>     * The updater correctly gets the paths and version information from GitHub. He then tries to download the latest release binary-only. Installation fails with the message like "no plugin for current OS found", despite beeing in the ZIP.

I followed up on this. I have two DLLs in the download asset, onje for 64bit and one for 32bit. They differ in name.
Maybe we should not search any DLL in the package, but if errors occur with this, try to narrow the search down to try to get the very same file name from the ZIP that was previously loaded?
This way, we could easily solve the problem not only for windows but also for the macOS problem.

**Comment by Krzmbrzl** [comment]
> Maybe we should not search any DLL in the package, but if errors occur with this, try to narrow the search down to try to get the very same file name from the ZIP that was previously loaded?

I'm quite sure that we don't have access to that information at that point anymore due to the library being unloaded at that time. At least it _should_ be unloaded. Given the error message you posted I begin to doubt that this is the case though xD

**Comment by hbeni** [comment]
> Manually trying to install it [the ZIP package] through the plugin options yields some obscure message "invalid ZIP header"

Got another report of this issue part: https://forum.flightgear.org/viewtopic.php?p=386790#p386790

**Comment by Krzmbrzl** [comment]
I fixed the ambiguity issue for the plugins within a single archive in #5102.
This now uses the scheme described in the new documentation available at https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/Bundling.md

**Comment by Krzmbrzl** [comment]
@hbeni how are you creating your zip files exactly? I can make the installer accept the zip file if I unzip its contents and the re-zip them using standard Windows10 tools (Send to > Compressed (zipped) folder).
However when I rezip the files using 7zip it does no longer work. Therefore it appears as if 7zip is zipping things differently than standard windows.
Also given the fact that on Linux it works just fine it seems that the library handling the zip stuff used in Mumble does perform stuff differently on Windows than it does on Linux :thinking:

**Comment by hbeni** [comment]
> I fixed the ambiguity issue for the plugins within a single archive in #5102.
> This now uses the scheme described in the new documentation available at https://github.com/mumble-voip/mumble/blob/master/docs/dev/plugins/Bundling.md

Thank you; the scheme does absolutely make sense.

> The archive must not contain anything besides the plugin libraries

However: Specifically in the light of the scheme check, we can easily now drop this constraint. It is (in my view) way too restrictive, as it even disallows for inclusion of LICENSE files (which, in my naive legal view, infers a violation of the GPL in my case :point_up:). As the updater is checking for the libs names now, we could drop this: The updater does only consider lib names containing the plugin name anyways!
I remember that you put in this constraint because you want to ship and update additional files in the future. But distributing (at least my plugin) with this constraint is not so good for end users. I have to release one package only with the binaries, and another one for all the other related stuff (like readmes, accompaning utils (I ship a small java utility, for example), etc). This leaves the user with the choice what exactly he needs to down,load initially. i would _vastly_ prefer one single release package containing all the stuff potentially needed.
A in my eyes good compromise would be, to weaken the constraint to this:  "The archive can contain arbitary files and strucutres. Every file starting with the plugin name is treated by the updater and are currently restricted to the plugin library files only." that in the future the updater will recognize the planned accompaning files (the ones you had in mind, not the custom ones I need) by the plugin name. This way you can still implement your planned feature, and plugin devs can ship whatever structure and additional files they want.
Another, maybe even more clean way would be to introduce some "mumble package description file / manifest", similar like JARs do. This file (xml?) could have a common known name the updater looks for and describe exactly and without disambiguity what files to update/search for in the archive, solving all our current issues (like map osType&architectures to binary names). That idea is also very flexible and extensible in the future.

----

> how are you creating your zip files exactly?

I package using makefile and githubs action, which both use the standard `zip` utility provided by the Ubuntu 20.04 runner:
- First, the makefile builds a ZIP: https://github.com/hbeni/fgcom-mumble/blob/9aecdcc2ce2bab038aafd37d5975bac3b975433b/client/mumble-plugin/makefile#L143-L152
- That ZIP is then updated/added with the macOS build: https://github.com/hbeni/fgcom-mumble/blob/9aecdcc2ce2bab038aafd37d5975bac3b975433b/.github/workflows/make-release.yml#L101

**Comment by Krzmbrzl** [comment]
> The updater does only consider lib names containing the plugin name anyways!

Nah that's not actually true. For backwards compatibility reasons it currently still considers every filename and only checks the suffix for handling clashes.

> I remember that you put in this constraint because you want to ship and update additional files in the future. But distributing (at least my plugin) with this constraint is not so good for end users. I have to release one package only with the binaries, and another one for all the other related stuff (like readmes, accompaning utils (I ship a small java utility, for example), etc). This leaves the user with the choice what exactly he needs to down,load initially. i would vastly prefer one single release package containing all the stuff potentially needed.

Just because the plugins happen to use a common file format (zip) it does not mean that you are supposed to put whatever stuff you like in it. This restriction will not be lifted.
Don't consider the plugin as a zip-file of your library files. Instead consider it as the cross-platform binary of your plugin that you then may embed into an actual zip for your release in which you can pack your license, READMEs and whatever else you like.
It might get clearer if you rename the library zip file to use the recommended `.mumble_plugin` file extension.

The manifest idea is a good one but as I said above the restrictions for additional files inside the actual plugin zip will not be lifted.

**Comment by hbeni** [comment]
> It might get clearer if you rename the library zip file to use the recommended .mumble_plugin file extension.

To rephrase in my own words: it's supposed like this?
- I distribute a ZIP with whatever files/structure I like (LICENSE, etc etc).
- Inside that ZIP is a special file "fgcom-mumble.mumble_plugin" which is a ZIP file containing all available plugin binarys for all platforms, adhering to the new naming scheme (or the stuff defined in the manifest file in the future)
- I can point the plugins updater/downloader to _my_ all-in-one distribution ZIP file and not the .mumble_plugin one

**Comment by Krzmbrzl** [comment]
All is correct except for

> I can point the plugins updater/downloader to my all-in-one distribution ZIP file and not the .mumble_plugin one

The updater has to be pointed to the actual plugin-zip. So in your case `fgcom-mumble.mumble_plugin`

**Comment by hbeni** [comment]
> All is correct except for
> 
> > I can point the plugins updater/downloader to my all-in-one distribution ZIP file and not the .mumble_plugin one
> 
> The updater has to be pointed to the actual plugin-zip. So in your case `fgcom-mumble.mumble_plugin`

That is exactly the spot where I have problems with: This forces me to upload and maintain two release packages, one for the initial download (containing all the stuff the user will need) and one special one for the updater, containing just the libs.
It could be solved if the updater/installer would extract and look for the manifest. This way i could bundle up all in one zip, considerably easing the download/install/update process of the user, as well as my deployment (I already had one complain about this very problem causing confusion to end users: https://github.com/hbeni/fgcom-mumble/issues/108)

Why the artifical constraint? If the updater/installer gets directed to a zip file (regardless if named `.mumble_plugin` or `.zip`), we could extract the file, look for the manifest and then let the manifest deal with the rest. As the manifest will be mandatory, and it will describe exactly and completely what is relevant for the installer, the rest of the zip does not matter to mumble.
This would be the best case for both of us :pleading_face: :pray:

**Comment by Krzmbrzl** [comment]
Again: Think of this as the actual binary instead of a zip. You don't pack READMEs or license files into binaries. But you still have to provide the binary in case you want a self-updating mechanism.

Don't consider the plugin as a zip file. I will not allow any clutter in the plugin zip in order to not have issues in the future if the format is to be changed.
Furthermore the end user is not supposed to know that the plugin bundle is really a zip because otherwise they will start messing around with them and break stuff and then go complain. Therefore the very notion of a user unpacking the plugin "binary" is wrong to begin with. That's not the semantics of how that is supposed to work.

Besides I think nowadays it names more sense to provide the binaries for download but keep Readmes available online. But that may only be my opinion on this.

**Comment by Krzmbrzl** [comment]
The extraction issue for the zip files should be fixed with #5106

**Comment by hbeni** [comment]
I think we talk at cross-purposes.... (talking about different layers)

> Switching the file extension to `.mumble_plugin` should clear the confusion as that should make clear what this thing is

That is perfectly fine. I just want to have this _inside_ another ZIP of my chosing.
Having the updater only supporting exactly that one file is my problem. I would prefer if the `.mumble_plugin` binary could be part of another release ZIP package, so i can ship more related stuff with it (I also ship a java client that supplies information to the plugin when it runs in the mumble instance, and like i said, also the license and readme files, and some other stuff like a FlightGear-addon so flightgear can send data to the plugin).

Like this structure:
- fgcom-mumble-release-1.0.0.zip
  - fgcom-mumble.mumble_plugin
    - fgcom-mumble.so
    - fgcom-mumble.bundle
    - fgcom-mumble.dll
  - REAMDE.md
  - LICENSE
  - radioGUI
  - FGFS-addon
  - ... more stuff

This currently actually works, but it is by accident and against the specs you wrote. The updater/installer just needs to recognize if he has a ZIP file. And if so, he needs to one-time look, if the ZIP contains a file `*.mumble_plugin`.

**Comment by Krzmbrzl** [comment]
Let's continue this discussion in #5107 as that has nothing to do with the original issue reported here :point_up:

**Comment by hbeni** [comment]
On windows I tested the installer today with `Mumble-1.4.0~2021-05-16~g789f2d7~snapshot.x64`
- When trying to install the `.mumble_plugin`, I still get "no plugin for current OS found" but it is there and referenced properly in the manifest.
- When unpacking the `.mumble_plugin` manually, I can install the `.dll` successfully.

**Comment by Krzmbrzl** [comment]
> Just have seen that the used (client-advertised) snapshot is a bit older and probably doesn't have the manifest stuff in yet.

Yes that is the case.

> When trying to install the .mumble_plugin, I still get "no plugin for current OS found" but it is there and referenced properly in the manifest.

You get that exact error message? If so, you are using a version of Mumble that does not contain the manifest changes yet.

> I tried the Azure snapshot from today (20210620.1) and that segfaults very fast after opening (when displaying the server list). I know this is not very helpful, but i cannot debug this in windows i think. And i think it's the same issue, Fahim already mentioned.

When does this Segfault happen? After you have installed your plugin or without any additional plugins installed?

**Comment by hbeni** [comment]
> > I tried the Azure snapshot from today (20210620.1) and that segfaults very fast after opening (when displaying the server list). I know this is not very helpful, but i cannot debug this in windows i think. And i think it's the same issue, Fahim already mentioned.
> 
> When does this Segfault happen? After you have installed your plugin or without any additional plugins installed?

I open mumble, then it starts and opens a window showing public servers. then the segfault happens.

If it happens without plugins, i need to recheck. Please stand by :)

**Comment by hbeni** [comment]
> If it happens without plugins, i need to recheck. Please stand by :)

Does _not_ happen - without plugin all seems fine.

**Comment by Krzmbrzl** [comment]
I ran it through the Visual Studio debugger and I am able to reproduce the crash:
> Unhandled exception at 0x000000006943C763 (fgcom-mumble.dll) in mumble.exe: 0xC00000FD: Stack overflow (parameters: 0x0000000000000001, 0x000000E017203FE8).

Aka: It seems you produce some sort of infinite recursion in your plugin.

The interesting bit is that the plugin does not even have to be enabled for this to occur. I'll try to find out more details but for the time being you can check whether at any point you are using recursive function calls (maybe indirect) that could lead to an infinite recursion.

**Comment by hbeni** [comment]
I don't think so.

Also, i just recompiled mumble on linux (64 bit) on commit e8f9d52555474e.

There in can install the `.mumble_plugin` and use it without any problems.
Why does it work on linux, but not on mac and windows.

**Comment by Krzmbrzl** [comment]
> There in can install the .mumble_plugin and use it without any problems.
Why does it work on linux, but not on mac and windows?

This is unrelated to the Segfault and is fixed with the manifest file.

I have tried to reproduce the crash with a Debug build of Mumble and there it does not happen. I strongly suspect that the infinite recursion is somehow related to the plugin update procedure which is skipped in Debug mode (and which is performed even if the plugin is unloaded).

**Comment by hbeni** [comment]
Hm, the update code of the plugin is all contained here: https://github.com/hbeni/fgcom-mumble/blob/master/client/mumble-plugin/lib/updater.cpp

Basically it:
- fetches the github release page
- parses the most recent tag name
- using that tag, fetches the header file defining the plugin version
- and compares that version to the local one
- Following that there is the download URL generated.

**Comment by Krzmbrzl** [comment]
> edit: the plugin does log what it does in the updater - that should display somewhere.

Not on Windows unfortunately as Windows does not show a programs output in the terminal :roll_eyes: 

So the infinite recursion happens when calling the `hasUpdate` function. In order to debug this more, I would require a build with debug symbols so I can step into the code.

However as it currently seems that this issue is not Mumble-related, let's continue the discussion in an issue over in your plugin's repo.

> edit2: and like said, it's the same code that works on linux here

:shrug: Then I guess _something_ shows platform-sepcific behavior

**Comment by hbeni** [comment]
> However as it currently seems that this issue is not Mumble-related, let's continue the discussion in an issue over in your plugin's repo.

Opened one here: https://github.com/hbeni/fgcom-mumble/issues/130

**Comment by hbeni** [comment]
What should still beeing investigated here is the issue that the `.mumble_plugin` is not detecting the windows `.dll` and macos `.bundle`.

**Comment by Krzmbrzl** [comment]
> What should still beeing investigated here is the issue that the .mumble_plugin is not detecting the windows .dll and macos .bundle.

No? You were using a version that does not use the manifest yet. That can't work :sweat_smile: 
I used a version on Windows that include the respective changes and it picked up the correct plugin without issues.

**Comment by hbeni** [comment]
Now confirming, the manifest install worked on windows, see https://github.com/hbeni/fgcom-mumble/issues/130#issuecomment-864889691

**Comment by hbeni** [comment]
Installing over the already installed plugin still shows a problem:
> ... does yield in a problem with the file in there not overwritable in AppData/Roaming.
> (probably the plugin is not unloaded in a complete or timely manner, still locking the library)

An idea why could be that the plugin does need a short while (0-2 seconds) to shut down all threads.
If mumble tries to unload and stop the plugin, it maybe does not wait for the threads to stop which could be the reason the operating system still has the DLL locked.
Maybe a workaround could be to try to delete the file in a short loop (say try it every half second for 5 seconds or so), before finally failing?

**Comment by Krzmbrzl** [comment]
It is the plugin's responsibility to make sure all threads it opened are closed once `mumble_shutdown` returns the control to Mumble. If that is not the case, then this is something that needs to be fixed by the plugin.

However my suspicion is that the DLL is locked because Mumble itself is still holding a reference to the DLL, thereby locking it.

I did not find the time to look into this issue yet though. But it is on my ToDo list :)

**Comment by hbeni** [comment]
> However my suspicion is that the DLL is locked because Mumble itself is still holding a reference to the DLL, thereby locking it.

I share this. FGCom-mumble does specifically wait in `mumble_shutdown()` for the threads to be done.

**Comment by Krzmbrzl** [comment]
I addressed the last issue reported here in #5152.

@hbeni however I was unable to make it work with your plugin. I reproduced the issue with a different plugin but for that it now works as expected.
It seems that something your plugin is doing keeps Windows locking the underlying file even when Mumble unloads the library completely. Any idea what that might be?

**Comment by hbeni** [comment]
No, not really; the only suspicious thing is probably the threading.
I will try a plugin debug build on windows, and see if the plugin logs something to the logfile.

**Comment by Krzmbrzl** [comment]
Something that could be tried is stripping functionality out of the build to check at which point it starts working as expected :thinking:

**Comment by hbeni** [comment]
What we can slo try is to see if its really mumble blocking the dll, or something else:
`tasklist /m [fgcom-mumble.dll]`

**Comment by hbeni** [comment]
Oh and again, whats strange is the fact that it works on Linux. So again it's OS specific.

**Comment by Krzmbrzl** [comment]
> Oh and again, whats strange is the fact that it works on Linux. So again it's OS specific.

It's not strange at all. Linux doesn't lock files that are used in a process. That's why there's no issue :)

> What we can slo try is to see if its really mumble blocking the dll, or something else:
tasklist /m fgcom-mumble.dll

I didn't check with this command but when I attempted to delete the DLL manually in the Windows explorer the error message told me that the DLL was "in use" by Mumble. So I'm rather confident that it is no other program that interferes here.

**Comment by hbeni** [comment]
> 
> 
> Something that could be tried is stripping functionality out of the build to check at which point it starts working as expected 🤔

Out of curiosity i added some build flags to exclude all the threads starting.
Even with no threads started, the problem persists. So most probably it's something else.
😕 😩

**Comment by hbeni** [comment]
whats also strange:
When i install fresh over (without previous plugin) installation succeeds (as usual).
Then you normaly activate the plugin by ticking the checkbox. When i don't it should not start the plugin when mumble starts, so i left it out in a fresh test. I closed mumble after install, and then started it again.
I would assume Mumble did not yet load the plugin at this state, right? Also i have nothing in my log and also nothing in my mumble chat window, suggesting me the plugin is not startet.
But even in this case, the locking appears.

☝️ Does this point to something I still do wrong with the updater api function hooks?
https://github.com/hbeni/fgcom-mumble/blob/9761d1d3eb773ce86c8d73a5e345009168f34946/client/mumble-plugin/lib/updater.cpp#L353-L404

**Comment by Krzmbrzl** [comment]
> But even in this case, the locking appears.

Yes this is expected. However what is not expected is that when you open the settings, select the plugin and then hit `Unload` it is still locked. For the other plugin that I tested, unloading cleared the locks :thinking:

> Does this point to something I still do wrong with the updater api function hooks?

I don't think so since I was running a Debug build of Mumble when this happened to me and the Debug build skips checking for updates altogether...

**Comment by hbeni** [comment]
(Just for the Archives): https://github.com/hbeni/fgcom-mumble/issues/131#issuecomment-870005462

> But! Out of curiosity I crosscompiled the testPlugin.cpp, AND i can reproduce the behavior with that!
> I compiled with this line: x86_64-w64-mingw32-g++-posix -fpic --shared -DMINGW_WIN64 -o testPlugin.dll testPlugin.cpp -static-libgcc -static-libstdc++ -O3 -Wl,-Bstatic -lstdc++ -lpthread -lws2_32
>
> Maybe we run into another mingw cross compilation problem here?

**Comment by hbeni** [comment]
Hi Robert,
sorry to bother again, but i hit another strange issue.
Today I released my plugin 0.14.2 version and tried to update it via the mumble updater.
This consistently triggered the "cannot remove old plugin file" issue we did think to have solved.

The base version I upgraded from was my previously test plugin versions; they still reported as 0.14.1.
You can download it here: https://github.com/hbeni/fgcom-mumble/actions/runs/1018765396
It should trigger an "upgrade please" message upon plugin loading.


Now, the interesting thing is, if I download the release manually, it will work and can remove/replace the old plugin file.
So maybe something in the mumble updater code is still locking?

**Comment by Krzmbrzl** [comment]
Yes indeed and I think I have already found the cause of the problem: Inside the updater code a handle to the plugin is created that is not reset before starting the plugin installer and thus the plugin can't get released.

I'll create a PR for you to test but I am quite sure that this is indeed the issue

**Comment by hbeni** [comment]
Very good catch, Robert!
Meanmwhile I did further test and confirm, it is *not* OpenSSL this time. It happens without OpenSSL compiled too.

**Comment by hbeni** [comment]
Can you provide me a build again? :pleading_face:

**Comment by Krzmbrzl** [comment]
> Can you provide me a build again?

You can download it from the CI server once CI has passed - see the link I posted for you in the PR :)
