### ISSUE TITLE
User state is moving to root channel after joining an online user to new channel

### ISSUE THREAD

**Issue by sebubd10** [mumble-voip/mumble#5128]
I am creating a new channel using Mumble .NET Core and joining two online users on this channel. This function is working fine with my local development & debugging using VS 2019, IIS, and .NET Core 3.1. But once I publish the API to the ubuntu server the user state is moving to the root channel by the server after joining an online user to new channel, but it's supposed to stay at the new channel.

Ubuntu Mumble Version: 1.3.4

**N.B: Even I tried to join the user to the new channel (One-To-One-81790895608746770342) through the android app, but no result. user is moving to the root channel.** 
***Please check the below steps done by the server:
moved to One-To-One-81790895608746770342 by the server.
moved in from One-To-One-81790895608746770342 by the server  (Unexpected Move)

.NET Core Code :

```
serverId = callee.SentraServerID;
mumbleChannelId = _mumbleServerClient.GetMumbleIceServerInstance().CreateChannel(callee.SentraServerID, channelName, 0);
if (mumbleChannelId > 0)
{
    var onlineCallerUser = server.GetOnlineUsers().Where(x => x.Value.Id == caller.SentraUserID).FirstOrDefault();
    if (onlineCallerUser.Value != null)
    {
        onlineCallerUser.Value.ChannelId = mumbleChannelId;
        server.UpdateUserState(onlineCallerUser.Value);
    }

    var onlineCalleeUser = server.GetOnlineUsers().Where(x => x.Value.Id == callee.SentraUserID).FirstOrDefault();
    if (onlineCalleeUser.Value != null)
    {
        onlineCalleeUser.Value.ChannelId = mumbleChannelId;
        server.UpdateUserState(onlineCalleeUser.Value);
    }

    if (onlineCallerUser.Value == null || onlineCalleeUser.Value == null)
    {
        //Remove channel
        if (mumbleChannelId > 0)
        {
            RemoveChannel(serverId, mumbleChannelId);
        }
        await SendCallEstablishFailedMessage(directTalkConfirmation);
    }
}
``

**Comment by Krzmbrzl** [comment]
I can't follow. First of all we don't provide any .NET API. Where is that coming from?

And what exactly are you trying to do and just when are users moved to the root channel? Maybe ti would be best if you could give a step-by-step description of what you are doing, what happens and what you would expect to happen :thinking:

**Comment by Kissaki** [comment]
> But once I publish the API to the ubuntu server the user state is moving to the root channel by the server after joining an online user to new channel, but it's supposed to stay at the new channel.

This sentence in particularly was very confusing to me and where you lost me.

**Comment by sebubd10** [comment]
@Kissaki and @Krzmbrzl  let me clear the problem in details: I am creating a one-to-one call facility for my mobile app, so mumble user_A call to user_B once user_B accept the call, I am creating a new mumble channel for these two users on the backend side (.NET Core) and assigning them to the channel by their mumble user ID. This functionality is perfectly working with my local server (IIS) during the testing. But when I deployed my ASP.NET Core project on the AWS Ubuntu server, the users' state is changing like this:

user_A  moved to One-To-One-81790895608746770342 by the server. (created channel)
user_A  moved in from One-To-One-81790895608746770342 by the server (Unexpected Move and goes to root channel)

user_B  moved to One-To-One-81790895608746770342 by the server. (created channel)
user_B  moved in from One-To-One-81790895608746770342 by the server (Unexpected Move and goes to root channel)

**Comment by Krzmbrzl** [comment]
Ah okay that makes the situation much clearer :+1: 

What I still don't quite understand though is what parts here are stock-Mumble and what parts did you write yourself? Did you write a custom server using a stock-client? Or the other way around? Or did you modify both? Or did you modify none and only use the server's RPC framework to do your manipulations?

**Comment by Krzmbrzl** [comment]
Did you verify that you don't accidentally delete the new channel after the two users have been moved into it?

**Comment by sebubd10** [comment]
@Krzmbrzl thanks for your reply. 

I am using Ice. I verified, there is no accidental delete. After pressing the hangup button I am deleting the channel. I have also checked locally with debug mode using Visual Studio 2019. The problem only with the live server.

**Comment by Krzmbrzl** [comment]
Is the live server and the one you are using locally the same version? If so, which version are you using?

**Comment by sebubd10** [comment]
Yes same Mumble Version: 1.3.4. Actually, I am using the same installed mumble-server on both sides.

**Comment by Krzmbrzl** [comment]
> CreateChannel(callee.SentraServerID, channelName, 0)

Where is this function coming from. I can't seem to find it in our Ice API :eyes:

**Comment by sebubd10** [comment]
@Krzmbrzl, Please let me try with a new mumble server.

**Comment by Krzmbrzl** [comment]
I don't assume that anything will change with that :thinking: 

However did you have set up any kind of ACL on any of your servers?

**Comment by sebubd10** [comment]
NO ACL in the OS end. open all ports / all traffic from AWS console to remove all kinds of ACL.

**Comment by Krzmbrzl** [comment]
Nah I meant inside Mumble. You can give certain users/groups specific permissions on a Mumble server
