### ISSUE TITLE
[W10] Application icon in task bar can become invisible

### ISSUE THREAD

**Issue by Porkepix** [mumble-voip/mumble#6631]
### Description

When opening other windows such as settings one and then closing it, there is some "replacement effect" where there's a visual effect showing the taskbar icon being replaced by something else.
Sometimes, what comes to replace… have no icon at all.

### Steps to reproduce

Repro rate is not 100%.
1. Open settings
2. Change for example language
3. Close settings
4. There's this taskbar icon replacement effect, and sometimes it replaces with something with no icon.

Reopening and closing settings after this reinstate the icon. But we can trigger the bug again after that.

This is a screenshot of… Mumble in the taskbar when the bug istriggered. Unfortunately I found no way of having the preview when hovering while taking the screenshot.
![Capture](https://github.com/user-attachments/assets/ac2be141-deaa-49c9-92fa-768a7f1ed36b)

### Mumble version

1.5.634

### Mumble component

Client

### OS

Windows

### Reproducible?

Yes

**Comment by Krzmbrzl** [comment]
@Hartmnt is this also fixed with your status bar icon rewrite?

**Comment by Hartmnt** [comment]
@Krzmbrzl Can not say for sure as I did not know about this problem on Windows before. But given that the tray icon implementation will be essentially rewritten entirely, it is more likely than not fixed with my PR. I guess OP has to test it at some point :)

**Comment by Hartmnt** [comment]
> It seems there might have some misunderstanding here. My issue is not about the notifications tray at the bottom right of the screen. It's about the large place at the bottom of the screen where the currently opened softwares are sitting.

Ah I see. So this would be a different problem then. Possibly related to the application icon maybe :thinking:

**Comment by garet-garet** [comment]
I did a kind of dynamic spectrum analysis on this, and I do not believe it is a control flow error, there is nothing I saw at the line level that suggests this is happening. I believe it may be something about how the icon is retrieved/cached incorrectly or some greater complicated dependency mess that I cannot begin to unravel.

**Comment by Krzmbrzl** [comment]
@garet-garet does that mean that you were unable to reproduce this issue?
